config/routes.rb
Rails.application.routes.draw do

  root :to => 'home#index'

  resources :locations

  resources :categories do
  collection { post :import }
end

  resources :products do
    get 'toggle_approve', :on => :member

    member do
      put "like" => "home#upvote"
      put "unlike" => "home#downvote"
    end

  end

  resources :surveys

  devise_for :admins

  devise_for :users

  get 'excel' => 'categories#excel'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')

  get 'home/product' => 'home#product_index'
  get 'home/category' => 'home#category_index'
  get 'home/about' => 'home#about'
  get 'home/terms' => 'home#terms'
  get 'home/contact' => 'home#contact'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :set_product, only: [:upvote, :downvote]

  before_action :authenticate_user!

  layout 'user_layout'

  respond_to :html

  def give_time
    @time = Time.now.utc.to_s.split(" ").second
    render :partial => 'shared/time_portion'
  end

  def index
    @home_categories = Category.all.where(:status => true)
    @banner_products = Product.all
  end

  def product_index
    
    @products = Product.all.where(:status => true, :category_id => params[:category])
    @paginate_products = Product.page(params[:page]).per(4)

  end

  def category_index

    @categories = Category.all.where(:status => true)
    @paginate_categories = Category.page(params[:page]).per(4)

  end

  def toggle_approve
    @products = Product.find(params[:id])
    @products.toggle!(:status)
    respond_to do |format|
      format.js
    end
  end

  def show
    @user = User.new
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      UserMailer.signup_confirmation(@user).deliver
      redirect_to @user, notice: "Signed up successfully"
    else
      render :new
    end
  end

  def upvote
    @product.upvote_from current_user
    redirect_to request.referrer
  end

  def downvote
    @product.downvote_from current_user
    redirect_to request.referrer
  end

  private
  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:product_name, :available_sizes, :available_colors, :category_id , :image, :status)
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.erb
<body class="">
<div class="container">
  <!-- form -->
  <div class="content inside-page about">


    <div class="row">
      <div class="col-sm-4">
        <h3><b>Mission</b></h3>
        <p>It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>

        <h3><b>Vision</b></h3>
        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>

      </div>
      <div class="col-sm-8">
        <h3><b>About Us</b></h3>
        <p>Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.</p>
        <p>The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from "de Finibus Bonorum et Malorum" by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.</p>
        <p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. </p>
      </div>
    </div>


  </div>
  <!-- form -->

</div>
</body>

app/views/home/category_index.html.erb
<body class="login_background">

<div class="jhelu-header">

</div>
<div class="container">
  <div class="row">
    <%= content_tag_for(:tr, @paginate_categories) do |category| %>
        <ul class="thumbnails col-md-3">

          <div class="thumbnail">
            <h3 class="text-center"><%= category.category_name %></h3>
            <div class="thumbnail thumb_height">
            <%= image_tag category.image , :class => "img-responsive"  %>
              </div>
            <div class="caption">

              <% if category.status == true %>
                  <p class="active text-center"><b>Status:</b> Active</p>
              <% else %>
                  <p class="inactive text-center"><b>Status:</b> Inactive</p>
              <% end %>
              <div class="text-center">

                <p><%= link_to home_product_path(:category => category.id)  , :class => 'btn btn-success' do %>
                    <span class="glyphicon glyphicon-level-up"></span>
                     Show Products
                <% end %>
                </p>

              <p class="text-center"><b>Description:</b> <%= category.description %></p>

              </div>

            </div>
          </div>
        </ul>
    <% end %>
  </div>

</div>

<div class="text-center">
  <%= paginate @paginate_categories , :pagination_class => "pagination-sm" %>
</div>

</body>

app/views/home/contact.html.erb
<body class="">
<div class="container">

  <!-- form -->
  <div class="content inside-page contact">

    <h2><b>Contact</b></h2>


    <div class="row">

      <div class="col-sm-12">
        <div class="map">
          <iframe src="https://www.google.com/maps/embed?pb=!1m23!1m12!1m3!1d3925.157856893241!2d123.93728709999998!3d10.3292492!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!4m8!3e6!4m0!4m5!1s0x33a999ac8a4df8c5%3A0x5011433b723246d6!2sA.S.Fortuna%2C+Mandaue+City%2C+Cebu!3m2!1d10.3292492!2d123.93728709999999!5e0!3m2!1sen!2sph!4v1437620865667" width="100%" height="300" frameborder="0"></iframe>
        </div>


        <div class="location col-sm-6 col-sm-offset-3">
          <h4>Ecommerce</h4>
          <p>A.S Fortuna St, Mandaue City, Cebu<br>
            +345 3456 34534
          </p>

          <h4>Write to us</h4>
          <form role="form">
            <div class="form-group">
              <input type="text" class="form-control" id="name" placeholder="Name">
            </div>
            <div class="form-group">
              <input type="email" class="form-control" id="email" placeholder="Enter email">
            </div>
            <div class="form-group">
              <input type="phone" class="form-control" id="phone" placeholder="Phone">
            </div>
            <div class="form-group">
              <textarea type="email" class="form-control"  placeholder="Message" rows="4"></textarea>
            </div>

              <%= link_to '' , :class => 'btn btn-primary' do %>
                  Send
              <% end %>

          </form>


        </div>





      </div>
    </div>
  </div>
  <!-- form -->

</div>

</body>

app/views/home/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  <%= favicon_link_tag 'logo.png' %>
  <title>Ecommerce</title>

</head>

<body class="carcasona-body">

<!--/.NAVBAR END-->

<section id="home" class="text-center">

  <div id="carousel-example" class="carousel slide" data-ride="carousel">

    <div class="carousel-inner">
      <div class="item active">

        <%= image_tag '1a.jpg' , :class => "img-responsive" , :alt => "slide" %>
        <div class="carousel-caption"><h2 class="animated fadeInDown">Leading brand of London & Paris</h2>
          <p class="animated fadeInUp">Lorem Ipsum is simply dummy text of the printing and typesetting industry</p>
        </div>
      </div>
      <div class="item">
        <%= image_tag '2a.jpg' , :class => "img-responsive"  , :alt => "slide" %>
        <div class="carousel-caption"><h2  class="animated fadeInDown">Leading brand of London & Paris</h2>
          <p class="animated fadeInUp">Lorem Ipsum is simply dummy text of the printing and typesetting industry</p>
        </div>
      </div>
      <div class="item">
        <%= image_tag '3a.JPG' , :class => "img-responsive" , :alt => "slide" %>
        <div class="carousel-caption"><h2  class="animated fadeInDown">Leading brand of London & Paris</h2>
          <p class="animated fadeInUp">Lorem Ipsum is simply dummy text of the printing and typesetting industry</p>
        </div>
      </div>
  </div>

    <ol class="carousel-indicators">
      <li data-target="#carousel-example" data-slide-to="0" class="active"></li>
      <li data-target="#carousel-example" data-slide-to="1"></li>
      <li data-target="#carousel-example" data-slide-to="2"></li>
    </ol>
  </div>

</section>
<!--/.SLIDESHOW END-->


</body>
</html>

app/views/home/product_index.html.erb
<body class="login_background">

<!--<div class="jhelu-header">-->

<!--</div>-->

<div class="container">
  <div class="row">
    <%= content_tag_for(:tr, @paginate_products) do |product| %>
        <ul class="thumbnails col-md-3">

          <div class="thumbnail">

            <h3 class="text-center"><%= product.product_name %></h3>
            <div class="thumbnail thumb_height">
            <%= image_tag product.image , :class => "img-responsive"%>
              </div>

            <div class="caption">
            <% if product.status == true %>
                <p class="active text-center hidden"><b>Status:</b> Active</p>
            <% else %>
                <p class="inactive text-center hidden"><b>Status:</b> Inactive</p>
            <% end %>
            <p class="text-center">
              <%= link_to home_category_path , :class => 'btn btn-primary' do %>
                  <span class="glyphicon glyphicon-shopping-cart"></span>
                  Add to Cart
              <% end %>
            </p>


              <p><b>Available Sizes:</b> <%= product.available_sizes %></p>
              <p><b>Available Colors:</b> <%= product.available_colors %></p>
              <p class="hidden"><b>Category:</b> <%= product.category.category_name %></p>

              <div class="caption text-center">
                <%= link_to like_product_path(product), class: "like", method: :put do %>
                    <button type="button" class="btn btn-info btn-xs" aria-label="Left Align">
                      <span class="glyphicon glyphicon-thumbs-up glyphicon-align-center" aria-hidden="true"></span>
                      <span class="badge"><%= product.get_upvotes.size %></span>
                    </button>
                <% end %>

                <%= link_to unlike_product_path(product), class: "like", method: :put do %>
                    <button type="button" class="btn btn-info btn-xs" aria-label="Left Align">
                      <span class="glyphicon glyphicon-thumbs-down glyphicon-align-center" aria-hidden="true"></span>
                      <span class="badge"><%= product.get_downvotes.size %></span>
                    </button>
                <% end %>

              </div>

            </div>
          </div>
        </ul>
    <% end %>
  </div>

</div>

<div class="text-center">
  <%= paginate @paginate_products , :pagination_class => "pagination-sm" %>
</div>

</body>