config/routes.rb
Rails.application.routes.draw do

  root :to => 'home#index'

  resources :locations

  resources :categories do
  collection { post :import }
end

  resources :products do
    get 'toggle_approve', :on => :member

    member do
      put "like" => "home#upvote"
      put "unlike" => "home#downvote"
    end

  end

  resources :surveys

  devise_for :admins

  devise_for :users

  get 'excel' => 'categories#excel'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')

  get 'home/product' => 'home#product_index'
  get 'home/category' => 'home#category_index'
  get 'home/about' => 'home#about'
  get 'home/terms' => 'home#terms'
  get 'home/contact' => 'home#contact'

end

app/models/category.rb
class Category < ActiveRecord::Base

  require 'csv'

  mount_uploader :image, ImageUploader

  has_many :products, :dependent => :destroy
  delegate :name, to: :category_name, prefix: true
  accepts_nested_attributes_for :products, allow_destroy: true

  validates :category_name, :description, presence: true,
            length: { minimum: 3 }




  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |category|
        csv << category.attributes.values_at(*column_names)
      end
    end
  end

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|

      category_hash = row.to_hash # exclude the price field
      category = Product.where(id: category_hash["id"])

      if category.count == 1
        category.first.update_attributes(category_hash.except("image")) # exclude the price field.
      else
        Category.create!(category_hash)
      end # end if !product.nil?
    end # end CSV.foreach
  end # end self.import(file)

  def self.open_spreadsheet(file)
    case File.extname(file.original_filename)
      when ".csv" then Csv.new(file.path, nil, :ignore)
      when ".xls" then Excel.new(file.path, nil, :ignore)
      when ".xlsx" then Excelx.new(file.path, nil, :ignore)
      else raise "Unknown file type: #{file.original_filename}"
    end
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!
  layout 'admin_layout'

  respond_to :html

  def index

    @categories = Category.all
    @paginate = Category.page(params[:page]).per(4)
    @category = Category.new

      respond_to do |format|
        format.html
        format.csv { send_data @categories.to_csv }
        format.xls # { send_data @products.to_csv(col_sep: "\t") }
      end

  end

  def excel

  end

  def import
    begin
      Category.import(params[:file])
      redirect_to categories_path, notice: "Products imported."
    rescue
      redirect_to categories_path, notice: "Invalid CSV file format."
    end
  end


  def show
    respond_with(@category)
  end

  def new
    @category = Category.new
    respond_with(@category)
  end

  def edit

  end


  def create
    @category = Category.new(category_params)
    @category.save
    redirect_to categories_path
    flash[:notice] = "Category Successfully Created"
  end

  def update
    @category.update(category_params)
    redirect_to categories_path
    flash[:notice] = "Category Successfully Updated"
  end

  def destroy
    @category.destroy
    respond_with(@category)
    flash[:notice] = "Category Successfully Destroyed"
  end

  private
    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:category_name, :description, :image, :status)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/views/categories/_form.html.erb
<%= nested_form_for(@category, html: {class: "form-horizontal", role: "form", remote: "true"}) do |f| %>

    <% if @category.errors.any? %>
        <div class="alert alert-danger alert-dismissable" role="alert">
          <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
          <h4><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h4>

          <ul>
            <% @category.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="form-group">
      <%= f.label :category_name, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_field :category_name, class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :description, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_field :description, class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :image, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.file_field :image, class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :status, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.check_box :status, class: "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.fields_for :products do |li| %>
            <%= li.text_field :product_name, class: "form-control" , placeholder: "Product Name" %><br />
            <%= li.text_field :available_sizes, class: "form-control" , placeholder: "Available Sizes" %><br />
            <%= li.text_field :available_colors, class: "form-control" , placeholder: "Available Colors" %><br />
            <%= li.file_field :image, class: "form-control" , placeholder: "Image" %><br />
            <%= li.check_box :status, class: "form-control" %><br />

            <%= li.link_to_remove "Remove item" , class: "btn btn-danger" %><br /><br />
        <% end %>
        <%= f.link_to_add "Add item", :products , class: "btn btn-success" %>
      </div>
    </div>


    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit class: "btn btn-primary" %>
      </div>
    </div>
<% end %>

app/views/categories/edit.html.erb
<div class="page-header">
  <%= link_to categories_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @category, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing category</h1>
</div>

<%= render 'form' %>

app/views/categories/excel.html.erb
<div class="page-header">
  </div>
<div class="btn-group nav navbar-nav">
  <%= form_tag @category, multipart: true do %>
      <%= file_field_tag :file , :class => "form-control col-sm-3 btn-group"%><br /><br />
      <%= submit_tag "Import" , class: 'btn btn-success' %>
  <% end %>
</div>

app/views/categories/index.html.erb
<div class="page-header">
  <%= link_to new_category_path, class: 'btn btn-primary' do %>
      <span class="glyphicon glyphicon-plus"></span>
      New Category
  <% end %>

  <h1 class="title glyphicon glyphicon-list-alt"> Listing Categories</h1>
</div>
<div class="container">
  <div class="row">
    <%= content_tag_for(:tr, @paginate) do |category| %>
    <ul class="thumbnails col-md-3">

        <div class="thumbnail">
          <h3 class="text-center"><%= category.category_name %></h3>
          <%= image_tag category.image , :class => "thumbnail thumb_height"  %>
          <% if category.status == true %>
              <p class="active text-center"><b>Status:</b> Active</p>
          <% else %>
              <p class="inactive text-center"><b>Status:</b> Inactive</p>
          <% end %>
          <div class="text-center">
          <%= link_to products_path(:category => category.id)  , :class => 'btn btn-success' do %>
                <span class="glyphicon glyphicon-plus"></span>
                Add Products
          <% end %>
          </div>
          <div class="caption">

            <p class="text-center"><b>Description:</b> <%= category.description %></p>
            <div class="glyphicon-jhelu">
              <%= link_to '', category, :class => "glyphicon glyphicon-book book" %>
              <%= link_to '', edit_category_path(category), :class => "glyphicon glyphicon-edit edit" %>
              <%= link_to '', category, method: :delete, data: {confirm: 'Are you sure?'}, :class => "glyphicon glyphicon-remove remove" %>
            </div>
          </div>
        </div>
     </ul>
    <% end %>
  </div>

</div>

<div class="text-center">
  <%= paginate @paginate , :pagination_class => "pagination-sm" %>
</div>

app/views/categories/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
          xmlns:o="urn:schemas-microsoft-com:office:office"
          xmlns:x="urn:schemas-microsoft-com:office:excel"
          xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
          xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">ID</Data></Cell>
        <Cell><Data ss:Type="String">Category Name</Data></Cell>
        <Cell><Data ss:Type="String">Description</Data></Cell>
        <Cell><Data ss:Type="String">Image</Data></Cell>
        <Cell><Data ss:Type="String">Status</Data></Cell>
      </Row>
      <% @categories.each do |category| %>
          <Row>
            <Cell><Data ss:Type="Number"><%= category.id %></Data></Cell>
            <Cell><Data ss:Type="String"><%= category.category_name %></Data></Cell>
            <Cell><Data ss:Type="String"><%= category.description %></Data></Cell>
            <Cell><Data ss:Type="String"><%= category.image %></Data></Cell>
            <Cell><Data ss:Type="Status"><%= category.status %></Data></Cell>
          </Row>
      <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/categories/new.html.erb
<div class="page-header">
  <%= link_to categories_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New category</h1>
</div>

<%= render 'form' %>

app/views/categories/show.html.erb
<div class="page-header">
  <%= link_to categories_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_category_path(@category), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1 class="glyphicon glyphicon-list-alt"> Show Categories</h1>
</div>

<dl class="dl-horizontal show-list">
  <dt>Category name:</dt>
  <dd><%= @category.category_name %></dd>

  <dt>Description:</dt>
  <dd><%= @category.description %></dd>

  <dd><% if @category.status == true %></dd>
      <dt>Status: Active</dt>
  <% else %>
      <dt>Status: Inactive</dt>
  <% end %>

  <dt>Image:</dt>

  <div class="col-md-4"><%=image_tag @category.image , :class => "thumbnail" %></div>

</dl>