config/routes.rb
Rails.application.routes.draw do

  root :to => 'home#index'

  resources :locations

  resources :categories do
  collection { post :import }
end

  resources :products do
    get 'toggle_approve', :on => :member

    member do
      put "like" => "home#upvote"
      put "unlike" => "home#downvote"
    end

  end

  resources :surveys

  devise_for :admins

  devise_for :users

  get 'excel' => 'categories#excel'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')

  get 'home/product' => 'home#product_index'
  get 'home/category' => 'home#category_index'
  get 'home/about' => 'home#about'
  get 'home/terms' => 'home#terms'
  get 'home/contact' => 'home#contact'

end

app/models/product.rb
class Product < ActiveRecord::Base
  acts_as_votable

  mount_uploader :image, ImageUploader

  belongs_to :category, :dependent => :destroy
  delegate :name, to: :category_name, prefix: true
  accepts_nested_attributes_for :category, allow_destroy: true

  validates_presence_of :category

  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |product|
        csv << product.attributes.values_at(*column_names)
      end
    end
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
  before_action :authenticate_admin!
  layout 'admin_layout'

  respond_to :html

  def index

    @category = Category.find(params[:category])
    @products = Product.all.where(:category_id => params[:category])
    @paginate = @products.page(params[:page]).per(4)
    # @product = Product.all.order(:cached_votes_score => :desc)

  end

  def show
    respond_with(@product)

  end

  def new
    @category = Category.find(params[:category])
    @product = Product.new
    respond_with(@product)
  end

  def edit
    @category = Category.find(params[:category])
  end

  def toggle_approve
    @products = Product.find(params[:id])
    @products.toggle!(:status)
    respond_to do |format|
      format.js
    end
  end

  def create
    @product = Product.new(product_params)
    @product.save
    respond_to do |format|
      format.html { redirect_to request.referrer, notice: 'Product was successfully created.' }
    end
  end

  def update
    @product.update(product_params)
    respond_to do |format|
      format.html { redirect_to request.referrer, notice: 'Product was successfully updated.' }
    end
  end

  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to request.referrer, notice: 'Product was successfully destroyed.' }
    end
  end

  def upvote
    @product.upvote_from current_admin
    redirect_to request.referrer
  end

  def downvote
    @product.downvote_from current_admin
    redirect_to request.referrer
  end

  private
  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:product_name, :available_sizes, :available_colors, :category_id , :image, :status, :category_attributes => [:id, :product_name, :available_sizes, :available_colors])
  end
end

app/helpers/products_helper.rb
module ProductsHelper

  def approve_link_text(approvable)
    approvable.status? ? 'Active' : 'Inactive'
  end

end

app/views/products/_form.html.erb
<%= nested_form_for(@product, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @product.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h4>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :product_name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :product_name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :available_sizes, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :available_sizes, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :available_colors, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :available_colors, class: "form-control" %>
    </div>
  </div>
    <div class="form-group">
      <%= f.label :image, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.file_field :image, class: "form-control" %>
      </div>
    </div>
    <div class="form-group hidden">
      <%= f.label :category_id , class: "col-sm-2 control-label"%>
      <div class="col-sm-10">
       <%= f.text_field :category_id , :value => @category.id %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :status, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.check_box :status, class: "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.fields_for :category do |li| %>
        <%= li.text_field :category_name, class: "form-control" , placeholder: "Category Name" %><br />
        <%= li.text_field :description, class: "form-control" , placeholder: "Description" %><br />
        <%= li.file_field :image, class: "form-control" , placeholder: "Image" %><br />
          <%= li.check_box :status, class: "form-control" %><br />

            <%= li.link_to_remove "Remove Item" , class: "btn btn-danger " %><br /><br />
        <% end %>
        <%= f.link_to_add "Add item", :category , class: "btn btn-success" %>
        </div>
      </div>



  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/products/edit.html.erb
<div class="page-header">
  <%= link_to products_path(:category => @category.id), class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @product, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing product</h1>
</div>

<%= render 'form' %>

app/views/products/index.html.erb
<div class="page-header">
  <%= link_to new_product_path(:category => @category.id), class: 'btn btn-primary' do %>
      <span class="glyphicon glyphicon-plus"></span>
      New Product
  <% end %>

  <h1 class="title glyphicon glyphicon-shopping-cart"> <%= @category.category_name  %> Products</h1>
</div>
<div class="container">
  <div class="row">
    <%= content_tag_for(:tr, @paginate) do |product| %>
        <ul class="thumbnails col-md-3">

          <div class="thumbnail">
            <h3 class="text-center"><%= product.product_name %></h3>
            <div class="thumbnail thumb_height">
            <%= image_tag product.image , :class => "img-responsive"  %>
              </div>

            <div class="caption">

              <p><%= link_to approve_link_text(product), toggle_approve_product_path(product), :remote => true, :id => "approve_link_#{product.id}" , :class => 'btn btn-success' %></p>

              <p><b>Available Sizes:</b> <%= product.available_sizes %></p>
              <p><b>Available Colors:</b> <%= product.available_colors %></p>
              <p><b>Category:</b> <%= product.category.category_name %></p>
              <div class="glyphicon-jhelu">
                <%= link_to '', product, :class => "glyphicon glyphicon-book book" %>
                <%= link_to '', edit_product_path(:id => product.id , :category => @category.id), :class => "glyphicon glyphicon-edit edit" %>
                <%= link_to '', product, method: :delete, data: {confirm: 'Are you sure?'}, :class => "glyphicon glyphicon-remove remove" %>
              </div>
            </div>
          </div>
        </ul>

    <% end %>
  </div>

</div>
<div class="text-center">
<%= paginate @paginate , :pagination_class => "pagination-sm" %>
</div>

<p>
  Download:
  <%= link_to "CSV", products_path(format: "csv") %> |
  <%= link_to "Excel", products_path(format: "xls") %>
</p>

app/views/products/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
          xmlns:o="urn:schemas-microsoft-com:office:office"
          xmlns:x="urn:schemas-microsoft-com:office:excel"
          xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
          xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">ID</Data></Cell>
        <Cell><Data ss:Type="String">Product Name</Data></Cell>
        <Cell><Data ss:Type="String">Available Sizes</Data></Cell>
        <Cell><Data ss:Type="String">Available Colors</Data></Cell>
      </Row>
      <% @products.each do |product| %>
          <Row>
            <Cell><Data ss:Type="Number"><%= product.id %></Data></Cell>
            <Cell><Data ss:Type="String"><%= product.product_name %></Data></Cell>
            <Cell><Data ss:Type="String"><%= product.available_sizes %></Data></Cell>
            <Cell><Data ss:Type="String"><%= product.available_colors %></Data></Cell>
          </Row>
      <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/products/new.html.erb
<div class="page-header">
  <%= link_to products_path(:category => @category.id), class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1><%= @category.category_name %> New product</h1>
</div>

<%= render 'form' %>

app/views/products/show.html.erb
<div class="page-header">
  <%= link_to products_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_product_path(@product), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1 class="glyphicon glyphicon-shopping-cart">Show Products</h1>
</div>

<dl class="dl-horizontal show-list">
  <dt>Product name:</dt>
  <dd><%= @product.product_name %></dd>

  <dt>Available sizes:</dt>
  <dd><%= @product.available_sizes %></dd>

  <dt>Available colors:</dt>
  <dd><%= @product.available_colors %></dd>

  <dt>Category:</dt>
  <dd><%= @product.category_id %></dd>

  <dd><% if @product.status == true %></dd>
        <dt>Status: Active</dt>
    <% else %>
        <dt>Status: Inactive</dt>
    <% end %>

  <dt>Image:</dt>

  <div class="col-md-4"><%=image_tag @product.image , :class => "thumbnail" %></div>

</dl>

app/views/products/toggle_approve.js.erb
$("#approve_link_<%= @products.id %>").text("<%= approve_link_text(@products) %>");
$("#product_<%= @products.id %>").effect("highlight");