config/routes.rb
Rails.application.routes.draw do

  root :to => 'home#index'

  resources :locations

  resources :categories do
  collection { post :import }
end

  resources :products do
    get 'toggle_approve', :on => :member

    member do
      put "like" => "home#upvote"
      put "unlike" => "home#downvote"
    end

  end

  resources :surveys

  devise_for :admins

  devise_for :users

  get 'excel' => 'categories#excel'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')

  get 'home/product' => 'home#product_index'
  get 'home/category' => 'home#category_index'
  get 'home/about' => 'home#about'
  get 'home/terms' => 'home#terms'
  get 'home/contact' => 'home#contact'

end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    @content_for_title = page_title.to_s
    @show_title = show_title
  end
  
  def show_title?
    @show_title
  end
  
  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end
  
  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/views/layouts/admin_layout.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <%= favicon_link_tag 'logo.png' %>
  <title>Ecommerce</title>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="admin_background">
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to image_tag 'logo.png' , :class => "header-logo" %>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="menu_link  <%= "active" if current_page?(root_path) %>">
          <a href="#home"><span class="glyphicon glyphicon-home"></span> Home</a></li>
        <li class="menu_link <%= "active " if current_page?(categories_path) %>">
        <a href="<%= categories_path %> "><span class="glyphicon glyphicon-th"></span>  Categories</a></li>
        <li class="menu_link <%= "active " if current_page?(excel_path) %>">
          <a href="<%= excel_path %> "><span class="glyphicon glyphicon-upload"></span>  Import Excel</a></li>
        <li><a href="#contact"><span class="glyphicon glyphicon-phone-alt"></span>  Contact</a></li>
      </ul>
      <ul class="nav navbar-nav pull-right">

        <% if admin_signed_in? %>
            <%= link_to destroy_admin_session_path, :method => :delete, class: 'btn btn-danger btn-logout' do %>
                <span class="glyphicon glyphicon-off"></span>
                Logout
            <% end %>

        <% end %>
      </ul>
    </div>
  </div>
</nav>
<div class="container">
  <% flash.each do |name, msg| %>
      <%= content_tag :div, class: "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do %>
          <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
          <%= msg %>
      <% end %>
  <% end %>

  <%= yield %>
</div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <%= favicon_link_tag 'logo.png' %>
  <title>Ecommerce</title>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= yield %>

</body>
</html>

app/views/layouts/user_layout.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  <meta name="description" content="">
  <meta name="author" content="">
  <%= favicon_link_tag 'logo.png' %>
  <title>Ecommerce</title>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar  navbar-inverse navbar-fixed-top" role="navigation">
  <div class="clearfix">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to image_tag 'logo.png' , :class => "header-logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->

    <!--<div class="collapse navbar-collapse navbar-right" id="bs-example-navbar-collapse-1">-->

    <div id="navbar" class="collapse navbar-collapse">

      <ul class="nav navbar-nav">
        <li class="dropdown">
        <li class="menu_link  <%= "active" if current_page?(root_path) %>">
          <a href="<%= root_path %> "><span class="glyphicon glyphicon-home"></span> Home</a></li>
        <li class="menu_link <%= "active " if current_page?(home_category_path) %>">
          <a href="<%= home_category_path %>"><span class="glyphicon glyphicon-th"></span> Categories</a></li>
        <li><a href="#">Checkout</a></li>
      </ul>

      <ul class="nav navbar-nav header-jhelu pull-right">

        <% if user_signed_in? %>

            <%= link_to destroy_user_session_path, :method => :delete, class: 'btn btn-danger btn-logout' do %>
                <span class="glyphicon glyphicon-off"></span>
                Logout
            <% end %>

        <% end %>
      </ul>

      <form class="navbar-form navbar-left searchbar" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search for Products">
        </div>
        <%= link_to home_category_path , :class => 'btn btn-warning' do %>
            <span class="glyphicon glyphicon-search"></span>
            Search
        <% end %>
        <div class="form-control">
        <%= Time.now.strftime("%m/%d/%Y") %>
        <%= Time.now.in_time_zone("Central Time (US & Canada)").to_s.split(" ").second  %>
        </div>
      </form>
      <div class="pull-right">
        <ul class="nav navbar-nav">

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-shopping-cart"></span> Cart <span class="cart-counter">2</span> <span class="caret"></span></a>
            <div class="dropdown-menu mini-cart">
              <div class="row product-list">
                <div class="col-xs-3"><a href="#"><%= image_tag '2.jpg' , :class => "img-responsive" , :alt => "product" %></a></div>
                <div class="col-xs-7"><a href="#">Blue Aeropostale Tshirt</a></div>
                <div class="col-xs-1"><a href="#"><i class="fa fa-close"></i></a></div>
              </div>

              <div class="row product-list">
                <div class="col-xs-3"><a href="#"><%= image_tag '6.jpg' , :class => "img-responsive" , :alt => "product" %></a></div>
                <div class="col-xs-7"><a href="#">Black JagThug Tshirt</a></div>
                <div class="col-xs-1"><a href="#"><i class="fa fa-close"></i></a></div>
              </div>

              <div class="clearfix">
                <a href="#" class="btn btn-primary pull-left">Continue shopping</a> <a href="#" class="btn btn-danger pull-right">Checkout</a>
              </div>

              <li><a href="#"  data-toggle="modal" data-target="#login"><span class="glyphicon glyphicon-user"></span> Login / Register</a></li>

            </div>
          </li>
        </ul>
      </div>
    </div><!-- Wnavbar-collapse -->
  </div><!-- container-fluid -->
</nav>
<!-- header -->

</div>
</div>
</nav>
<div class="container">
  <% flash.each do |name, msg| %>
      <%= content_tag :div, class: "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do %>
          <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
          <%= msg %>
      <% end %>
  <% end %>



</div>
<%= yield %>
</body>
</html>

<!-- login modal -->
<div class="modal fade" id="login">
  <div class="modal-dialog">
    <div class="modal-content">
      <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>


      <div class="row">
        <div class="col-sm-6">
          <h4>Sign In</h4>
          <div class="form-group">
            <label for="exampleInputEmail1">Email address</label>
            <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Enter email">
          </div>
          <div class="form-group">
            <label for="exampleInputPassword1">Password</label>
            <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
          </div>
          <div class="checkbox">
            <label>
              <input type="checkbox"> Remeber password
            </label>
          </div>
          <div class="forgot-password"><a href="#">Forgot Password</a></div>
          <button type="submit" class="btn btn-danger">Submit</button>
        </div>
        <div class="col-sm-6">
          <h4>Create an Account</h4>
          <p>I would like to create a new account. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce dolor tellus, tempor ut ultrices ferme ntum, aliquam consequat metus. </p>
          <a href="#" class="btn btn-danger">Create an Account</a>
          <br><br>
          <%= link_to "Sign in with Facebook", "users/auth/facebook", id: "sign_in" , :class => "btn btn-primary" %>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- login modal -->

<!-- footer -->
<div class="footer navbar-fixed-bottom" role="navigation">
  <div class="pull-left">
    <form class="navbar-form navbar-left newsletter" role="search">
      <div class="form-group">
        <input type="text" class="form-control" placeholder="Enter Your Email Id Here">
      </div>
      <button type="submit" class="btn btn-inverse">Subscribe</button>
    </form>
    <div class="links">
      <a href="<%= home_about_path %>">About </a>
      <a href="<%= home_terms_path %>">Terms & Condition </a>
      <a href="<%= home_contact_path %>">Contact </a>
    </div>
  </div>

  <div class="social pull-right">
    <a href="https://www.facebook.com/"><i class="fa fa-facebook-square" data-toggle="tooltip" data-placement="top" data-original-title="facebook"></i></a>
    <a href="https://www.instagram.com/"><i class="fa fa-instagram"  data-toggle="tooltip" data-placement="top" data-original-title="instragram"></i></a>
    <a href="https://www.twitter.com/"><i class="fa fa-twitter-square" data-toggle="tooltip" data-placement="top" data-original-title="twitter"></i></a>
    <a href="https://www.pinterest.com/"><i class="fa fa-pinterest-square" data-toggle="tooltip" data-placement="top" data-original-title="pinterest"></i></a>
    <a href="https://www.tumblr.com/"><i class="fa fa-tumblr-square" data-toggle="tooltip" data-placement="top" data-original-title="tumblr"></i></a>
    <a href="https://www.youtube.com/"><i class="fa fa-youtube-square" data-toggle="tooltip" data-placement="top" data-original-title="youtube"></i></a>
  </div>
</div>

<!-- footer -->